import { EnvironmentPreset } from '../types/skybox';

export const DEFAULT_PRESETS: EnvironmentPreset[] = [
  {
    id: 'clear-day',
    name: 'Clear Desert Day',
    timeOfDayHour: 13.5,
    atmosphere: {
      globalBrightness: 1.0,
      summerFilter: true,
      shadeMode: 'original',
      skyColor: '#3a88d6',
      fogColor: '#b8daf2',
      ambientLightColor: '#d8eefa',
      sunLightColor: '#fffbf0',
      ambientIntensity: 1.25,
      sunIntensity: 2.5,
      waterGlintColor: '#fff0d0',
    },
    gradient: {
      skyMode: 'gradient_clouds',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#2a5090',
      midSkyColor: '#4f8bc9',
      horizonColor: '#b8daf2',
      gradientCurvePower: 1.2,
      midHeightOffset: 0.22,
      sunFlareGlow: 0.7,
      horizonBandGlow: 0.45,
    },
    clouds: {
      cloudCoverage: 0.45,
      cloudEdge: 0.06,
      cloudSpeed: 0.018,
      skyZenith: '#3a88d6',
      skyHorizon: '#b8daf2',
      cloudColor: '#fffcf5',
      cloudShadow: '#8ca4c8',
      stormTurbulence: 0,
      stormDarken: 0,
      cloudOpacity: 1.0,
      cloudAltitude: 1200,
      cloudThickness: 350,
      weather: 'clear',
    },
    sunGodRays: {
      sunHeight: 49,
      sunAzimuth: 45,
      lockSunToPlayer: true,
      sunDiscSize: 1.8,
      colorTemperature: 5500,
      godRaysEnable: true,
      rayIntensity: 0.6,
      rayDensity: 0.5,
      rayDecay: 0.92,
      lumGateMin: 0.8,
      lumGateMax: 0.98,
      highlightRolloff: 0.75,
      horizonGlow: 0.45,
      rayColorInner: '#fff6d3',
      rayColorOuter: '#ffcb7c',
    },
    fog: {
      globalFog: true,
      startDist: 150,
      endDist: 3000,
      densityMultiplier: 0.75,
      altitudeScale: 1.2,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: false,
      dropSize: 2.0,
      intensity: 1.0,
      windX: 1.0,
      windZ: 0.5,
      wind: true,
      windTrails: true,
    },
  },
  {
    id: 'sunset-dusk',
    name: 'Ghibli Sunset Bloom',
    timeOfDayHour: 18.75,
    atmosphere: {
      globalBrightness: 1.15,
      summerFilter: true,
      shadeMode: 'ghibli',
      skyColor: '#b4324f',
      fogColor: '#f78361',
      ambientLightColor: '#f9c58d',
      sunLightColor: '#ffeaad',
      ambientIntensity: 1.4,
      sunIntensity: 3.2,
      waterGlintColor: '#ffe599',
    },
    gradient: {
      skyMode: 'gradient_clouds',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#202464',
      midSkyColor: '#c85078',
      horizonColor: '#ffa07a',
      gradientCurvePower: 1.4,
      midHeightOffset: 0.18,
      sunFlareGlow: 0.95,
      horizonBandGlow: 0.7,
    },
    clouds: {
      cloudCoverage: 0.55,
      cloudEdge: 0.08,
      cloudSpeed: 0.02,
      skyZenith: '#6b3272',
      skyHorizon: '#ff8a5c',
      cloudColor: '#ffe6b8',
      cloudShadow: '#7a3e65',
      stormTurbulence: 0.1,
      stormDarken: 0,
      cloudOpacity: 0.95,
      cloudAltitude: 1400,
      cloudThickness: 400,
      weather: 'clear',
    },
    sunGodRays: {
      sunHeight: 6,
      sunAzimuth: 260,
      lockSunToPlayer: false,
      sunDiscSize: 2.4,
      colorTemperature: 2800,
      godRaysEnable: true,
      rayIntensity: 0.85,
      rayDensity: 0.65,
      rayDecay: 0.94,
      lumGateMin: 0.72,
      lumGateMax: 0.95,
      highlightRolloff: 0.82,
      horizonGlow: 0.85,
      rayColorInner: '#fff3c4',
      rayColorOuter: '#ff7733',
    },
    fog: {
      globalFog: true,
      startDist: 100,
      endDist: 2500,
      densityMultiplier: 0.85,
      altitudeScale: 1.5,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: false,
      dropSize: 2.0,
      intensity: 1.0,
      windX: 1.5,
      windZ: 0.8,
      wind: true,
      windTrails: true,
    },
  },
  {
    id: 'midnight-stars',
    name: 'Midnight Moon & Stars',
    timeOfDayHour: 23.5,
    atmosphere: {
      globalBrightness: 0.85,
      summerFilter: false,
      shadeMode: 'cinematic',
      skyColor: '#0a1024',
      fogColor: '#121b36',
      ambientLightColor: '#24355a',
      sunLightColor: '#a6c8ff',
      ambientIntensity: 0.75,
      sunIntensity: 1.2,
      waterGlintColor: '#c8e0ff',
    },
    gradient: {
      skyMode: 'deep_night',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#040714',
      midSkyColor: '#0c1630',
      horizonColor: '#1a274c',
      gradientCurvePower: 1.8,
      midHeightOffset: 0.15,
      sunFlareGlow: 0.3,
      horizonBandGlow: 0.25,
    },
    clouds: {
      cloudCoverage: 0.35,
      cloudEdge: 0.12,
      cloudSpeed: 0.012,
      skyZenith: '#050916',
      skyHorizon: '#162244',
      cloudColor: '#455982',
      cloudShadow: '#0d152a',
      stormTurbulence: 0,
      stormDarken: 0,
      cloudOpacity: 0.8,
      cloudAltitude: 1600,
      cloudThickness: 300,
      weather: 'clear',
    },
    sunGodRays: {
      sunHeight: -45, // Under horizon, moon is opposite at +45
      sunAzimuth: 180,
      lockSunToPlayer: false,
      sunDiscSize: 1.4,
      colorTemperature: 8500,
      godRaysEnable: true,
      rayIntensity: 0.35,
      rayDensity: 0.4,
      rayDecay: 0.88,
      lumGateMin: 0.85,
      lumGateMax: 0.99,
      highlightRolloff: 0.6,
      horizonGlow: 0.2,
      rayColorInner: '#d8e8ff',
      rayColorOuter: '#6688cc',
    },
    fog: {
      globalFog: true,
      startDist: 200,
      endDist: 3500,
      densityMultiplier: 0.6,
      altitudeScale: 1.0,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: false,
      dropSize: 1.5,
      intensity: 0.8,
      windX: 0.5,
      windZ: 0.2,
      wind: false,
      windTrails: false,
    },
  },
  {
    id: 'rain-storm',
    name: 'Overcast Rain & God Rays',
    timeOfDayHour: 15.0,
    atmosphere: {
      globalBrightness: 0.8,
      summerFilter: false,
      shadeMode: 'vibrant',
      skyColor: '#3d4857',
      fogColor: '#4a5768',
      ambientLightColor: '#6c7a8c',
      sunLightColor: '#fff5d6',
      ambientIntensity: 1.1,
      sunIntensity: 3.5,
      waterGlintColor: '#ffffff',
    },
    gradient: {
      skyMode: 'gradient_clouds',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#2b3442',
      midSkyColor: '#4d5d73',
      horizonColor: '#6e7e94',
      gradientCurvePower: 1.1,
      midHeightOffset: 0.3,
      sunFlareGlow: 0.85,
      horizonBandGlow: 0.35,
    },
    clouds: {
      cloudCoverage: 0.82,
      cloudEdge: 0.04,
      cloudSpeed: 0.035,
      skyZenith: '#323d4d',
      skyHorizon: '#5b697d',
      cloudColor: '#d6dfe8',
      cloudShadow: '#28313e',
      stormTurbulence: 0.7,
      stormDarken: 0.45,
      cloudOpacity: 1.0,
      cloudAltitude: 900,
      cloudThickness: 600,
      weather: 'rain',
    },
    sunGodRays: {
      sunHeight: 38,
      sunAzimuth: 130,
      lockSunToPlayer: false,
      sunDiscSize: 2.0,
      colorTemperature: 5000,
      godRaysEnable: true,
      rayIntensity: 0.95,
      rayDensity: 0.75,
      rayDecay: 0.96,
      lumGateMin: 0.65,
      lumGateMax: 0.95,
      highlightRolloff: 0.9,
      horizonGlow: 0.5,
      rayColorInner: '#fffae6',
      rayColorOuter: '#ffe08a',
    },
    fog: {
      globalFog: true,
      startDist: 80,
      endDist: 1800,
      densityMultiplier: 1.3,
      altitudeScale: 1.8,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: true,
      dropSize: 2.4,
      intensity: 2.2,
      windX: 2.2,
      windZ: 1.2,
      wind: true,
      windTrails: true,
    },
  },
  {
    id: 'misty-dawn',
    name: 'Misty Alpine Dawn',
    timeOfDayHour: 6.2,
    atmosphere: {
      globalBrightness: 1.05,
      summerFilter: false,
      shadeMode: 'original',
      skyColor: '#6380a6',
      fogColor: '#e0d8eb',
      ambientLightColor: '#ebd9ec',
      sunLightColor: '#ffecd1',
      ambientIntensity: 1.3,
      sunIntensity: 2.8,
      waterGlintColor: '#ffeedd',
    },
    gradient: {
      skyMode: 'gradient_clouds',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#2b4470',
      midSkyColor: '#8a82ab',
      horizonColor: '#f7cfb8',
      gradientCurvePower: 1.35,
      midHeightOffset: 0.25,
      sunFlareGlow: 0.8,
      horizonBandGlow: 0.6,
    },
    clouds: {
      cloudCoverage: 0.4,
      cloudEdge: 0.08,
      cloudSpeed: 0.014,
      skyZenith: '#3a598c',
      skyHorizon: '#e0c7ba',
      cloudColor: '#fff5ea',
      cloudShadow: '#847f9c',
      stormTurbulence: 0,
      stormDarken: 0,
      cloudOpacity: 0.88,
      cloudAltitude: 1100,
      cloudThickness: 320,
      weather: 'foggy',
    },
    sunGodRays: {
      sunHeight: 8,
      sunAzimuth: 80,
      lockSunToPlayer: false,
      sunDiscSize: 1.9,
      colorTemperature: 3600,
      godRaysEnable: true,
      rayIntensity: 0.75,
      rayDensity: 0.55,
      rayDecay: 0.93,
      lumGateMin: 0.75,
      lumGateMax: 0.96,
      highlightRolloff: 0.8,
      horizonGlow: 0.7,
      rayColorInner: '#fff1d6',
      rayColorOuter: '#ffa670',
    },
    fog: {
      globalFog: true,
      startDist: 50,
      endDist: 1400,
      densityMultiplier: 1.6,
      altitudeScale: 2.0,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: false,
      dropSize: 1.5,
      intensity: 0.5,
      windX: 0.5,
      windZ: 0.2,
      wind: true,
      windTrails: false,
    },
  },
  {
    id: 'cyber-aurora',
    name: 'Cyberpunk Aurora Night',
    timeOfDayHour: 1.0,
    atmosphere: {
      globalBrightness: 1.1,
      summerFilter: false,
      shadeMode: 'stylized',
      skyColor: '#051329',
      fogColor: '#0d283d',
      ambientLightColor: '#1d5e69',
      sunLightColor: '#00ffcc',
      ambientIntensity: 1.0,
      sunIntensity: 1.8,
      waterGlintColor: '#00ffaa',
    },
    gradient: {
      skyMode: 'deep_night',
      proceduralSkyDome: true,
      enableProceduralClouds: true,
      enableGradientCurve: true,
      zenithColor: '#020512',
      midSkyColor: '#0b3954',
      horizonColor: '#087e8b',
      gradientCurvePower: 1.6,
      midHeightOffset: 0.28,
      sunFlareGlow: 0.5,
      horizonBandGlow: 0.65,
    },
    clouds: {
      cloudCoverage: 0.5,
      cloudEdge: 0.1,
      cloudSpeed: 0.025,
      skyZenith: '#041026',
      skyHorizon: '#0e5663',
      cloudColor: '#39d9b8',
      cloudShadow: '#0b263b',
      stormTurbulence: 0.2,
      stormDarken: 0,
      cloudOpacity: 0.9,
      cloudAltitude: 1500,
      cloudThickness: 450,
      weather: 'clear',
    },
    sunGodRays: {
      sunHeight: -30,
      sunAzimuth: 220,
      lockSunToPlayer: false,
      sunDiscSize: 1.5,
      colorTemperature: 9500,
      godRaysEnable: true,
      rayIntensity: 0.7,
      rayDensity: 0.6,
      rayDecay: 0.92,
      lumGateMin: 0.7,
      lumGateMax: 0.97,
      highlightRolloff: 0.75,
      horizonGlow: 0.6,
      rayColorInner: '#c4fff3',
      rayColorOuter: '#00b4d8',
    },
    fog: {
      globalFog: true,
      startDist: 120,
      endDist: 2800,
      densityMultiplier: 0.9,
      altitudeScale: 1.4,
      altitudeAutoExpand: true,
    },
    rain: {
      enableRain: false,
      dropSize: 2.0,
      intensity: 1.0,
      windX: 1.0,
      windZ: 0.5,
      wind: true,
      windTrails: true,
    },
  },
];

export const DISTANCE_FOG_PRESETS: Record<string, { startDist: number; endDist: number; densityMultiplier: number; altitudeScale: number }> = {
  'Balanced (Default)': { startDist: 150, endDist: 3000, densityMultiplier: 0.75, altitudeScale: 1.2 },
  'Vast Horizon': { startDist: 400, endDist: 8000, densityMultiplier: 0.4, altitudeScale: 0.8 },
  'Dense Mountain Mist': { startDist: 40, endDist: 1200, densityMultiplier: 1.8, altitudeScale: 2.2 },
  'Deep Atmosphere': { startDist: 100, endDist: 4500, densityMultiplier: 1.1, altitudeScale: 1.6 },
  'Close Dramatic Fog': { startDist: 20, endDist: 600, densityMultiplier: 2.5, altitudeScale: 3.0 },
};
